name: Build and Push Docker Images
on:
  push:
    branches:
      - devops/github-actions

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: argocd-helm-envsubst-plugin
  DOCKERFILE_PATH: Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image (AMD)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ${{ env.DOCKERFILE_PATH }} \
            --tag ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
            --push .
